### ISSUE TITLE
Mark homework 1, exercise 1,2  of Peigen Zhou

### ISSUE THREAD

**Issue by BaconZhou** [BaconZhou/stat679work#1]
# Homework1

The SHA is 659e3596f5271fbf4772eeb35b982b3225488e74
The homework fold [hw1](https://github.com/BaconZhou/stat679work/tree/master/hw1) is inside the [stat679work](https://github.com/BaconZhou/stat679work) repo.
## Exercise 1-3

Inside HW1, I already wrote all the things I have done into readme.md file [check here](https://github.com/BaconZhou/stat679work/blob/master/hw1/readme.md), which contains:
- Scripts purpose
- Command I used
- Full code snapshots
- Summary table

Professor @cecileane, I also add a makefile to execute all commands in hw1.

Best,
Peigen

**Comment by cecileane** [comment]
Hi Peigen,

Great work! You even have a makefile, this is fantastic. And for this, you added an "undoNormalizeFileNames" script to clean the project. Fantastic! Are you sure that you will be learning something from this course? You could add a target called "all" so that we can type `make` to do it all. I had to change the name of your filename from `makeFile` to `makefile`, and I had to do `make clean` first, but after that it worked beautifully.

It's all super well documented.
You also have a license for your repository, great choice, I highly approve.

Your script to normalize (or un-normalize) file names is elegant in its design. It would have been better, however, to use `timetest${i}_snaq.log` instead of `timetest$i\_snaq.log`. Generally, it is good practice to access shell variables with `${i}` instead of `$i`.

Unfortunately, you didn't fully use this exercise to practice with `grep`. It was one of the main goals of this homework. None of your commands used _extended_ regular expressions. It is great that you used parameter expansion and a clever use of `cut` with various delimiters, but learning to use extended regular expressions would be useful for all other languages, not just the shell.

Last small thing: in a csv file, there should be not spaces before/after the commas that delimit the columns. Well, another small thing: I didn't have it in my list, but "hahahaha" is not a good message for a git commit...

Please close this issue, or [assign](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) it to me and I can close it.

**Comment by BaconZhou** [comment]
Hi, Professor @cecileane 
Thanks for all your comment for this home work, my new commit is here 199c88cba05b4b9eded4d9ed49c742d5f8c76193

I took the Professor Karl Broman's course before, which was a fantastic course as yours too. So that I am trying to acquire this habits to start a makefile of all my projects.

For the `makeFile`, that is a mistake, I forgot use `git rm --cached makeFile`.....
And I change all the summary script, and now use _extended regular expressions_, here is the [Code](https://github.com/BaconZhou/stat679work/blob/master/hw1/scripts/summarizeSNaQres.sh)

Thanks for your effort!
Best,
Peigen
