### ISSUE TITLE
Mark homework 2 of Peigen Zhou

### ISSUE THREAD

**Issue by BaconZhou** [BaconZhou/stat679work#3]
Hi Professor @cecileane

The SHA is 6b86f8e81947ca8f5d8c6cf0ed5eaf6c596784d1
The homework fold [hw2](https://github.com/BaconZhou/stat679work/tree/master/hw2) is inside the [stat679work](https://github.com/BaconZhou/stat679work) repo.

## Python

Inside HW2, I already wrote all the things I have done into readme.md file [check here](https://github.com/BaconZhou/stat679work/blob/master/hw2/readme.md), which contains:

- Software version
- Directory
- Command suggestion
- Basic assumption for future usage
- Mergy table glance

Best,
Peigen

**Comment by cecileane** [comment]
Hi Peigen,

Very nice job! Your work was easy to go through. More details below.

## overall presentation

Excellent! You made great use of markdown style, with links from the issue to the readme file straight. It is great that you took note of the Python version that you used. I did not check that your code works with Python 2, but is is awesome that you planned for it (using functions from the `__future__` module). Your documents are nicely organized with different directories for the script, input/output files. It is also fantastic that you explicitly wrote down assumptions on the input file format and content. Another assumption was that the last line of the energy file is the "Total" (in your code this last line is ignored, regardless of whether is says "Total" or not).

## running your script

It's too bad that didn't use the argparse module. Your readme file explains the usage very well, but if the arguments are not quite as expected, the user is not given a useful message by the script itself:

```shell
$ python script/data.py
Traceback (most recent call last):
  File "script/data.py", line 7, in <module>
    with open(arg[1]) as f:
IndexError: list index out of range
```

or

```shell
$ python script/data.py data/energy.csv data/waterTemperature.csv
Traceback (most recent call last):
  File "script/data.py", line 18, in <module>
    assert i[0].split(' ')[1] == '00:00:00', print("Energy data format maybe wrong")
IndexError: list index out of range
```

Unfortunately, your output is missing a comma at the end of each line that does not have an energy value. A comma should be there, to signify that there is another column, with a missing value in it. Your output was like this:

    "Plot Title: 10679014 jackson July29"
    "#","Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)","energy"
    1,07/29/16 10:26:34 AM,72.86
    2,07/29/16 11:26:34 AM,73.92
    3,07/29/16 12:26:34 PM,73.98
    ...
    13,07/29/16 10:26:34 PM,73.27
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30
    ...

instead of this (see the extra commas):

    "Plot Title: 10679014 jackson July29"
    "#","Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)","energy"
    1,07/29/16 10:26:34 AM,72.86,
    2,07/29/16 11:26:34 AM,73.92,
    3,07/29/16 12:26:34 PM,73.98,
    ...
    13,07/29/16 10:26:34 PM,73.27,
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30,
    ...

## about your code

Your code is very sleak. It would have been best to define functions, instead of having all in one straight chunk. Functions make it easier to test bits of code (you can test one function at a time). It also helps make your code more human-readable. For example, your code on lines 13-19 could have made the body of a function named `check_energy_timeformat`. A colleague or yourself in 6 months would not need to read the code inside the function, to guess what the function is doing.

When you use `assert` to check for an assumption, the error message should be the second item in the tuple, not a print statement. You had this on line 18:

```python
assert i[0].split(' ')[1] == '00:00:00', print("Energy data format maybe wrong")
```

you should have had this instead (where I made the error message more explicit):

```python
assert i[0].split(' ')[1] == '00:00:00', "wrong format for energy data: should be logged at time 00:00:00"
```

This strange line:

```python
temperature[0][0] = temperature[0][0].replace('\xef\xbb\xbf','').replace('\r\r','')
```

(line 34) has no comment to explain why this line is needed and what it does. This is probably tied to an assumption in the temperature file: best to have a comment to talk about this assumption.
The following block of code would also benefit from more comments. Instead of `try`ing to access the 4th argument like this:

```python
try:
  with open(arg[3],'w') as f:
    ...
except IndexError:
```

it would would have been best to check for the length of `arg`. If less than 4, print to stdout. If 4 (or more), print to file.
If would also have been advantageous to have a function to do the printing, because lines 40-41 and 45 are supposed to do the same thing, and this thing is missing the comma on lines that do not have an energy value. So there is a bug to fix. If it's in a function, the bug needs to be fixed only once. Otherwise, it's easy to fix the bug in one place and forget the other.

Anyway, great job overall!
